
"use client"

import type React from "react"
import { useMemo, useState } from "react"
import Link from "next/link"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion"
import {
  Check,
  ChevronRight,
  MessageCircle,
  BarChart3,
  Sparkles,
  Search,
  ShieldCheck,
  LayoutDashboard,
  FileText,
  Users,
  Zap,
  Lock,
  Mail,
} from "lucide-react"

type ResearchType = "interview" | "diary"

function generateInsight(topic: string, type: ResearchType): string {
  const seed = topic.trim().replace(/\s+/g, " ")
  if (!seed) {
    return type === "interview"
      ? "Enter a research topic above to see how WhatsApp AI interviews generate deeper insights than traditional surveys."
      : "Type a research question to see how AI-powered diary studies capture authentic user behaviors over time."
  }

  if (type === "interview") {
    return `🎯 Key Insight: ${seed}

📊 WhatsApp Response Rate: 89% (vs 12% email)
⏱️ Average Session: 8.5 minutes
💬 Follow-up Questions: 4.2 per participant

Top Themes:
• Pain point: "Current solutions feel impersonal"
• Preference: "WhatsApp feels more natural to me"
• Behavior: Users respond 3x faster on WhatsApp

💡 Recommendation: Focus on personalized, conversational experiences that mirror WhatsApp's familiar interface.`
  }

  // diary study
  return `📱 7-Day Diary Study: ${seed}

📈 Engagement: 94% completion rate
🔄 Daily Check-ins: 6.8/7 average
📝 Rich Context: 2.3x more detailed responses

Behavioral Patterns:
• Peak usage: 7-9 PM weekdays
• Context: "I use this when commuting"
• Friction: "Too many steps to complete task"

🎯 Insight: Users prefer micro-interactions during transition moments. Simplify onboarding flow.`
}

function ResponseRateChart() {
  return (
    <div className="space-y-3">
      <div className="flex items-center justify-between text-sm">
        <span>WhatsApp</span>
        <span className="font-semibold text-primary">
          89%
        </span>
      </div>
      <div className="h-2 rounded-full overflow-hidden bg-muted">
        <div className="h-full rounded-full bg-primary" style={{ width: "89%"}} />
      </div>

      <div className="flex items-center justify-between text-sm">
        <span>Email</span>
        <span className="font-semibold text-muted-foreground">
          12%
        </span>
      </div>
      <div className="h-2 rounded-full overflow-hidden bg-muted">
        <div className="h-full rounded-full bg-muted-foreground/50" style={{ width: "12%"}} />
      </div>

      <div className="flex items-center justify-between text-sm">
        <span>SMS</span>
        <span className="font-semibold text-muted-foreground">
          23%
        </span>
      </div>
      <div className="h-2 rounded-full overflow-hidden bg-muted">
        <div className="h-full rounded-full bg-muted-foreground/50" style={{ width: "23%" }} />
      </div>
    </div>
  )
}

function ResearchPreview({
  topic = "",
  type = "interview",
}: {
  topic?: string
  type?: ResearchType
}) {
  const content = useMemo(() => generateInsight(topic || "", type), [topic, type])

  return (
    <div className="rounded-xl border bg-card text-card-foreground shadow-sm">
      <div className="flex items-center justify-between px-4 py-3 border-b">
        <div className="flex items-center gap-2">
          <span
            className="inline-flex items-center gap-1.5 rounded-md px-2 py-1 text-xs font-medium border bg-primary text-primary-foreground"
          >
            <MessageCircle className="h-3.5 w-3.5" />
            <span className="capitalize">{type === "interview" ? "AI Interview" : "Diary Study"}</span>
          </span>
        </div>
        <div className="flex items-center gap-1.5">
          <div className="h-2 w-2 rounded-full bg-primary" />
          <div className="h-2 w-2 rounded-full bg-muted-foreground/30" />
          <div className="h-2 w-2 rounded-full bg-muted-foreground/30" />
        </div>
      </div>
      <div className="p-4">
        <div className="flex items-start gap-3">
          <div className="h-8 w-8 rounded-full flex items-center justify-center bg-accent">
            <BarChart3 className="h-4 w-4 text-accent-foreground" />
          </div>
          <div className="flex-1">
            <div className="flex items-center gap-2">
              <div className="font-semibold">Research Insights</div>
              <span className="text-xs text-muted-foreground">· Generated by AI</span>
            </div>
            <p className="whitespace-pre-wrap text-sm leading-relaxed mt-1">{content}</p>
          </div>
        </div>
      </div>
    </div>
  )
}


function StepCard({
  step = 1,
  title = "Step",
  description = "Description",
  icon = <Sparkles className="h-5 w-5" />,
}: {
  step?: number
  title?: string
  description?: string
  icon?: React.ReactNode
}) {
  return (
    <div className="relative rounded-xl border bg-card p-5 text-card-foreground shadow-sm">
      <div className="absolute -top-3 left-5 rounded-full border bg-card px-2 py-0.5 text-xs font-medium">
        Step {step}
      </div>
      <div className="flex items-start gap-3">
        <div
          className="h-9 w-9 rounded-md flex items-center justify-center shrink-0 bg-primary/10 text-primary"
        >
          {icon}
        </div>
        <div>
          <div className="font-medium">{title}</div>
          <p className="text-sm text-muted-foreground mt-1">{description}</p>
        </div>
      </div>
    </div>
  )
}

function IntegrationCard({
  title = "Integration",
  description = "Description",
  icon = <Sparkles className="h-5 w-5" />,
}: {
  title?: string
  description?: string
  icon?: React.ReactNode
}) {
  return (
    <div className="rounded-xl border bg-card p-5 text-card-foreground shadow-sm">
      <div className="flex items-center gap-3">
        <div className="h-10 w-10 rounded-md bg-muted flex items-center justify-center">{icon}</div>
        <div className="font-medium text-base">{title}</div>
      </div>
      <p className="text-sm text-muted-foreground mt-2">{description}</p>
    </div>
  )
}

export default function Page() {
  const [topic, setTopic] = useState<string>("Understanding why users abandon our mobile app onboarding process")

  return (
    <div className="bg-background text-foreground">
      {/* Hero */}
      <section className="relative overflow-hidden bg-accent">
        <div
          className="absolute inset-0 -z-10"
          aria-hidden="true"
        />
        <header className="container flex items-center justify-between py-5 px-4 md:px-6">
          <Link href="/" className="flex items-center gap-2">
            <div
              className="inline-flex h-9 w-9 items-center justify-center rounded-md text-primary-foreground bg-primary shadow"
            >
              <Search className="h-5 w-5" />
            </div>
            <span className="font-semibold text-lg tracking-tight">ResearchAI</span>
            <span className="sr-only">ResearchAI home</span>
          </Link>
          <nav className="hidden md:flex items-center gap-6 text-sm">
            <Link href="#features" className="text-muted-foreground hover:text-foreground">
              Features
            </Link>
            <Link href="/use-cases" className="text-muted-foreground hover:text-foreground">
              Use Cases
            </Link>
            <Link href="#integrations" className="text-muted-foreground hover:text-foreground">
              Integrations
            </Link>
            <Link href="#faq" className="text-muted-foreground hover:text-foreground">
              FAQ
            </Link>
          </nav>
          <div className="flex items-center gap-2">
            <Button asChild variant="ghost" className="hidden sm:inline-flex">
              <Link href="#try">Try the demo</Link>
            </Button>
            <Button asChild>
              <Link href="#cta">Get Started</Link>
            </Button>
          </div>
        </header>

        <div className="container px-4 md:px-6 py-16 lg:py-24">
          <div className="grid gap-10 lg:grid-cols-2 lg:gap-12 items-center">
            <div className="space-y-6">
              <Badge variant="outline" className="bg-card border-primary/50 text-primary font-medium">
                New • WhatsApp-powered research
              </Badge>
              <h1 className="text-3xl sm:text-5xl font-bold tracking-tight">
                Tap into Deeper Data with WhatsApp AI Research
              </h1>
              <p className="text-muted-foreground text-lg">
                Unlock authentic user insights through WhatsApp AI interviews and digital diary studies. Achieve
                significantly higher response rates compared to email, with AI-assisted analysis tailored for African
                and emerging markets.
              </p>
              <div className="flex flex-col sm:flex-row gap-3">
                <Button>
                  <Sparkles className="h-4 w-4 mr-2" />
                  Get Started
                </Button>
                <Button variant="outline" asChild>
                  <Link href="#try">
                    <ChevronRight className="h-4 w-4 mr-2" />
                    See the demo
                  </Link>
                </Button>
              </div>
              <div className="flex items-center gap-4 text-sm text-muted-foreground">
                <div className="inline-flex items-center gap-1.5">
                  <ShieldCheck className="h-4 w-4 text-primary" />
                  POPIA compliant
                </div>
                <div className="inline-flex items-center gap-1.5">
                  <Lock className="h-4 w-4 text-primary" />
                  Secure data
                </div>
                <div className="inline-flex items-center gap-1.5">
                  <BarChart3 className="h-4 w-4 text-primary" />
                  89% response rate
                </div>
              </div>
            </div>

            {/* Interactive preview */}
            <div id="try" className="lg:ml-auto w-full animate-float">
              <Card className="shadow-lg">
                <CardHeader className="space-y-2">
                  <CardTitle className="text-base md:text-lg">Try it: AI research insights</CardTitle>
                  <p className="text-sm text-muted-foreground">
                    Enter a research question. See how WhatsApp AI generates deeper insights.
                  </p>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div className="flex items-start gap-2">
                    <div className="relative flex-1">
                      <Input
                        aria-label="Your research question"
                        placeholder="e.g., Why do users drop off during our checkout?"
                        value={topic}
                        onChange={(e) => setTopic(e.target.value)}
                      />
                    </div>
                    <Button variant="secondary" type="button" onClick={() => setTopic("")}>
                      Clear
                    </Button>
                  </div>

                  <Tabs defaultValue="interview" className="w-full">
                    <TabsList className="grid grid-cols-2">
                      <TabsTrigger value="interview" className="flex items-center gap-2">
                        <MessageCircle className="h-4 w-4" /> AI Interview
                      </TabsTrigger>
                      <TabsTrigger value="diary" className="flex items-center gap-2">
                        <FileText className="h-4 w-4" /> Diary Study
                      </TabsTrigger>
                    </TabsList>
                    <TabsContent value="interview" className="mt-4">
                      <ResearchPreview type="interview" topic={topic} />
                    </TabsContent>
                    <TabsContent value="diary" className="mt-4">
                      <ResearchPreview type="diary" topic={topic} />
                    </TabsContent>
                  </Tabs>

                  <div className="mt-4 p-4 bg-muted/50 rounded-lg">
                    <h4 className="text-sm font-medium mb-3">Response Rate Comparison</h4>
                    <ResponseRateChart />
                  </div>
                </CardContent>
              </Card>
            </div>
          </div>

          {/* Social proof */}
          <div className="mt-16 md:mt-24">
            <p className="text-center text-xs uppercase tracking-widest text-muted-foreground mb-6">
              Trusted by research teams across Africa and emerging markets
            </p>
            <div className="flex flex-wrap justify-center items-center gap-x-12 gap-y-6">
              <span className="text-muted-foreground font-medium text-lg">Company A</span>
              <span className="text-muted-foreground font-medium text-lg">Enterprise B</span>
              <span className="text-muted-foreground font-medium text-lg">Startup C</span>
              <span className="text-muted-foreground font-medium text-lg">Org D</span>
               <span className="text-muted-foreground font-medium text-lg">Agency E</span>
            </div>
          </div>
        </div>
      </section>

      {/* Features */}
      <section id="features" className="py-16 md:py-24 bg-background">
        <div className="container px-4 md:px-6">
          <div className="mx-auto max-w-2xl text-center">
            <Badge variant="outline" className="border-primary/50 text-primary font-medium">
              Why ResearchAI
            </Badge>
            <h2 className="mt-3 text-2xl sm:text-4xl font-bold tracking-tight">
              Higher engagement. Deeper insights. Faster results.
            </h2>
            <p className="mt-4 text-muted-foreground max-w-xl mx-auto">
              WhatsApp-powered research delivers 7x higher response rates with AI-assisted analysis.
            </p>
          </div>
          <div className="mt-12 grid gap-6 sm:grid-cols-2 lg:grid-cols-4">
            <Card className="bg-card">
              <CardHeader>
                <div className="h-10 w-10 rounded-md flex items-center justify-center bg-primary/10 text-primary">
                  <MessageCircle className="h-5 w-5" />
                </div>
                <CardTitle className="text-lg">WhatsApp AI interviews</CardTitle>
              </CardHeader>
              <CardContent className="text-sm text-muted-foreground">
                Conduct natural, conversational interviews through WhatsApp with AI-powered follow-up questions and
                real-time insights.
              </CardContent>
            </Card>
            <Card className="bg-card">
              <CardHeader>
                <div className="h-10 w-10 rounded-md flex items-center justify-center bg-primary/10 text-primary">
                  <FileText className="h-5 w-5" />
                </div>
                <CardTitle className="text-lg">Digital diary studies</CardTitle>
              </CardHeader>
              <CardContent className="text-sm text-muted-foreground">
                Capture authentic behaviors over time with AI-assisted prompts and automated analysis of user journeys.
              </CardContent>
            </Card>
            <Card className="bg-card">
              <CardHeader>
                <div className="h-10 w-10 rounded-md flex items-center justify-center bg-primary/10 text-primary">
                  <Users className="h-5 w-5" />
                </div>
                <CardTitle className="text-lg">Smart panel management</CardTitle>
              </CardHeader>
              <CardContent className="text-sm text-muted-foreground">
                Multi-channel outreach via Email, SMS, and WhatsApp with automated scheduling and participant tracking.
              </CardContent>
            </Card>
            <Card className="bg-card">
              <CardHeader>
                <div className="h-10 w-10 rounded-md flex items-center justify-center bg-primary/10 text-primary">
                  <BarChart3 className="h-5 w-5" />
                </div>
                <CardTitle className="text-lg">AI-powered insights</CardTitle>
              </CardHeader>
              <CardContent className="text-sm text-muted-foreground">
                Automated theme extraction, sentiment analysis, and actionable recommendations from unstructured data.
              </CardContent>
            </Card>
          </div>
        </div>
      </section>

      {/* How it works */}
      <section id="how-it-works" className="py-16 md:py-24 bg-secondary">
        <div className="container px-4 md:px-6">
          <div className="mx-auto max-w-2xl text-center">
             <Badge variant="outline" className="bg-card border-primary/50 text-primary font-medium">Workflow</Badge>
            <h2 className="mt-3 text-2xl sm:text-4xl font-bold tracking-tight">
              From research question to insights in four steps
            </h2>
          </div>
          <div className="mt-12 grid gap-6 md:grid-cols-4">
            <StepCard
              step={1}
              title="Setup study"
              description="Define research objectives, target demographics, and choose WhatsApp interviews or diary studies."
              icon={<LayoutDashboard className="h-5 w-5" />}
            />
            <StepCard
              step={2}
              title="Recruit participants"
              description="Multi-channel outreach via Email, SMS, and WhatsApp with automated follow-ups and scheduling."
              icon={<Users className="h-5 w-5" />}
            />
            <StepCard
              step={3}
              title="Collect data"
              description="AI-powered WhatsApp conversations with smart follow-up questions and real-time engagement tracking."
              icon={<MessageCircle className="h-5 w-5" />}
            />
            <StepCard
              step={4}
              title="Generate insights"
              description="Automated analysis with theme extraction, sentiment scoring, and actionable recommendations."
              icon={<BarChart3 className="h-5 w-5" />}
            />
          </div>
        </div>
      </section>

      {/* Templates showcase */}
      <section className="py-16 md:py-24 bg-background">
        <div className="container px-4 md:px-6">
          <div className="mx-auto max-w-2xl text-center">
             <Badge variant="outline" className="border-primary/50 text-primary font-medium">
              Research Templates
            </Badge>
            <h2 className="mt-3 text-2xl sm:text-4xl font-bold tracking-tight">Start with proven methodologies</h2>
            <p className="mt-4 text-muted-foreground max-w-xl mx-auto">
              Pre-built research frameworks optimized for WhatsApp engagement and African markets.
            </p>
          </div>

          <div className="mt-10 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
            {[
              "User Journey Mapping",
              "Product Feedback Loop",
              "Brand Perception Study",
              "Usability Testing",
              "Customer Satisfaction",
              "Market Entry Research",
            ].map((t) => (
              <div key={t} className="flex items-center justify-between rounded-md border bg-card px-4 py-3 shadow-sm">
                <div className="flex items-center gap-3">
                  <Zap className="h-4 w-4 text-primary" />
                  <span className="text-sm font-medium">{t}</span>
                </div>
                <Button variant="ghost" size="sm" asChild>
                  <Link href="#cta">Use</Link>
                </Button>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Integrations */}
      <section id="integrations" className="py-16 md:py-24 bg-secondary">
        <div className="container px-4 md:px-6">
          <div className="mx-auto max-w-2xl text-center">
            <Badge variant="outline" className="bg-card border-primary/50 text-primary font-medium">
              Integrations
            </Badge>
            <h2 className="mt-3 text-2xl sm:text-4xl font-bold tracking-tight">Connect with your research stack</h2>
            <p className="mt-4 text-muted-foreground max-w-xl mx-auto">
              Seamless integration with popular research and analytics tools.
            </p>
          </div>
          <div className="mt-12 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
            <IntegrationCard
              title="WhatsApp Business"
              icon={<MessageCircle className="h-5 w-5" />}
              description="Direct integration for high-engagement research conversations."
            />
            <IntegrationCard
              title="Multi-channel outreach"
              icon={<Mail className="h-5 w-5" />}
              description="Email, SMS, and WhatsApp recruitment with automated follow-ups."
            />
            <IntegrationCard
              title="Analytics platforms"
              icon={<BarChart3 className="h-5 w-5" />}
              description="Export insights to Tableau, Power BI, and other analytics tools."
            />
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section id="faq" className="py-16 md:py-24 bg-background">
        <div className="container px-4 md:px-6">
          <div className="mx-auto max-w-2xl text-center">
            <Badge variant="outline" className="border-primary/50 text-primary font-medium">FAQ</Badge>
            <h2 className="mt-3 text-2xl sm:text-4xl font-bold tracking-tight">Common questions</h2>
          </div>
          <div className="mx-auto mt-10 max-w-3xl">
            <Accordion type="single" collapsible className="w-full space-y-3">
              <AccordionItem value="a1" className="border rounded-md bg-card px-4">
                <AccordionTrigger className="text-base hover:no-underline">Why is WhatsApp more effective than email for research?</AccordionTrigger>
                <AccordionContent className="text-muted-foreground">
                  WhatsApp achieves 89% response rates vs 12% for email because it feels more personal and
                  conversational. Participants are more likely to engage authentically in a familiar messaging
                  environment.
                </AccordionContent>
              </AccordionItem>
              <AccordionItem value="a2" className="border rounded-md bg-card px-4">
                <AccordionTrigger className="text-base hover:no-underline">Which markets and languages are supported?</AccordionTrigger>
                <AccordionContent className="text-muted-foreground">
                  We specialize in African and emerging markets with support for English, French, Portuguese, Arabic,
                  and major local languages. Our AI is trained on regional communication patterns.
                </AccordionContent>
              </AccordionItem>
              <AccordionItem value="a3" className="border rounded-md bg-card px-4">
                <AccordionTrigger className="text-base hover:no-underline">How does AI assist with research analysis?</AccordionTrigger>
                <AccordionContent className="text-muted-foreground">
                  Our AI automatically extracts themes, performs sentiment analysis, identifies behavioral patterns, and
                  generates actionable insights from unstructured conversation data, saving weeks of manual analysis.
                </AccordionContent>
              </AccordionItem>
              <AccordionItem value="a4" className="border rounded-md bg-card px-4">
                <AccordionTrigger className="text-base hover:no-underline">Is participant data secure and POPIA compliant?</AccordionTrigger>
                <AccordionContent className="text-muted-foreground">
                  Yes. We're fully POPIA compliant with end-to-end encryption, secure data storage, and participant
                  consent management. Data is anonymized and can be deleted upon request.
                </AccordionContent>
              </AccordionItem>
            </Accordion>
          </div>
        </div>
      </section>

      {/* Final CTA */}
      <section id="cta" className="py-16 md:py-24 bg-secondary">
        <div className="container px-4 md:px-6">
          <div className="mx-auto max-w-2xl text-center">
            <h2 className="text-2xl sm:text-4xl font-bold tracking-tight">Stop guessing. Start understanding.</h2>
            <p className="mt-4 text-muted-foreground max-w-xl mx-auto">
              Get deeper insights with WhatsApp-powered AI research. Join leading teams across Africa and emerging
              markets.
            </p>
          </div>
          <div className="mx-auto mt-8 max-w-md">
            <form
              onSubmit={(e) => {
                e.preventDefault()
                alert("Thanks! We'll be in touch soon.")
              }}
              className="flex gap-2"
              aria-label="Get started with ResearchAI"
            >
              <Input type="email" required placeholder="you@company.com" aria-label="Email address" className="bg-card" />
              <Button type="submit">
                <Mail className="h-4 w-4 mr-2" />
                Get Started
              </Button>
            </form>
            <p className="mt-3 text-xs text-muted-foreground">Free consultation. No spam. POPIA compliant.</p>
          </div>
          <div className="mx-auto mt-6 max-w-md space-y-2 text-sm">
            <div className="flex items-center gap-2">
              <Check className="h-4 w-4 text-primary" />
              <span>89% response rates with WhatsApp interviews</span>
            </div>
            <div className="flex items-center gap-2">
              <Check className="h-4 w-4 text-primary" />
              <span>AI-powered insights and analysis</span>
            </div>
            <div className="flex items-center gap-2">
              <Check className="h-4 w-4 text-primary" />
              <span>POPIA compliant and secure</span>
            </div>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t bg-background">
        <div className="container px-4 md:px-6 py-8 flex flex-col sm:flex-row items-center gap-4">
          <div className="flex items-center gap-2">
            <div
              className="inline-flex h-8 w-8 items-center justify-center rounded-md text-primary-foreground bg-primary"
            >
              <Search className="h-4 w-4" />
            </div>
            <span className="font-semibold">ResearchAI</span>
          </div>
          <div className="sm:ml-auto flex items-center gap-6 text-sm">
            <Link href="#features" className="text-muted-foreground hover:text-foreground">
              Features
            </Link>
             <Link href="/use-cases" className="text-muted-foreground hover:text-foreground">
              Use Cases
            </Link>
            <Link href="#integrations" className="text-muted-foreground hover:text-foreground">
              Integrations
            </Link>
             <Link href="#" className="text-muted-foreground hover:text-foreground">
              Privacy
            </Link>
            <Link href="#" className="text-muted-foreground hover:text-foreground">
              Terms
            </Link>
          </div>
        </div>
        <div className="container px-4 md:px-6 pb-8 text-xs text-center sm:text-left text-muted-foreground">
          © {new Date().getFullYear()} ResearchAI. All rights reserved.
        </div>
      </footer>
    </div>
  )
}
